[technote]
id = "SITCOMTN-168"
series_id = "SITCOMTN"
canonical_url = "https://sitcomtn-168.lsst.io"
github_url = "https://github.com/lsst-sitcom/sitcomtn-168"
github_default_branch = "main"
date_created = 2025-07-25T17:34:53Z
organization.name = "NSF-DOE Vera C. Rubin Observatory"
organization.ror = "https://ror.org/048g3cy84"
license.id = "CC-BY-4.0"

[technote.status]
state = "draft"

[[technote.authors]]
name.given = "Craig S."
name.family = "Lage"
internal_id = "lagecs"

[[technote.authors.affiliations]]
name = "University of California, Davis"
internal_id = "UCDavis"
address = "Davis"
